[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[completion]
activate_on_typing = true
copilot = false

[mcp]
presets = []

[mcp.mcpServers]

[server]
browser = "default"
follow_symlink = false

[datasources]

[snippets]
include_default_snippets = true
custom_paths = []

[runtime]
default_auto_download = []
reactive_tests = true
auto_reload = "off"
default_sql_output = "auto"
output_max_bytes = 8000000
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
auto_instantiate = true
watcher_on_save = "lazy"
pythonpath = []

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[diagnostics]
sql_linter = true
enabled = true

[ai]
inline_tooltip = false
mode = "manual"
rules = ""

[ai.models]
displayed_models = []
custom_models = []

[formatting]
line_length = 79

[display]
theme = "dark"
default_table_page_size = 10
dataframes = "rich"
code_editor_font_size = 16
cell_output = "below"
default_table_max_columns = 50
reference_highlighting = false
default_width = "full"

[experimental]

[language_servers.basedpyright]
enabled = true

[language_servers.pylsp]
enabled = false
enable_ruff = true
enable_pylint = false
enable_flake8 = false
enable_pyflakes = false
enable_pydocstyle = false
enable_mypy = true

[language_servers.ty]
enabled = false

[package_management]
manager = "pixi"
